# Generated by Django 4.2.6 on 2023-10-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('programming_language', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Senior', 'Senior'), ('Middle', 'Middle'), ('Junior', 'Junior')], max_length=10)),
            ],
        ),
    ]
